apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: compute-service
  name: compute-service
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: compute-service
    spec:
      containers:
      - image: gcr.io/microassignment-199111/compute-service:v1
        name: compute-service
        ports:
        - containerPort: 9090

