apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: web-service
  name: web-service
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-service
    spec:
      containers:
      - image: gcr.io/microassignment-199111/web-service:v1
        imagePullPolicy: Always
        name: web-service
        ports:
        - containerPort: 8080

      
