#! /bin/bash
kubectl delete services compute-service

kubectl delete deployments compute-service

docker build -t compute-service ComputeService

docker tag compute-service gcr.io/microassignment-199111/compute-service:v1

docker push gcr.io/microassignment-199111/compute-service:v1

kubectl create -f Deployments/compute-service-deployment.yaml

kubectl create -f Services/compute-service-service.yaml
