#! /bin/bash


kubectl delete services compute-service

kubectl delete services web-service



kubectl delete deployments compute-service

kubectl delete deployments web-service

docker build -t compute-service ComputeService

docker tag compute-service gcr.io/microassignment-199111/compute-service:v1

docker push gcr.io/microassignment-199111/compute-service:v1

docker build -t web-service WebService

docker tag web-service gcr.io/microassignment-199111/web-service:v1

docker push gcr.io/microassignment-199111/web-service:v1

kubectl create -f Deployments/compute-service-deployment.yaml

kubectl create -f Deployments/web-service-deployment.yaml

kubectl create -f Services/compute-service-service.yaml

kubectl create -f Services/web-service-service.yaml
