#! /bin/bash
kubectl delete services web-service

kubectl delete deployments web-service

docker build -t web-service WebService

docker tag web-service gcr.io/microassignment-199111/web-service:v1

docker push gcr.io/microassignment-199111/web-service:v1

kubectl create -f Deployments/web-service-deployment.yaml

kubectl create -f Services/web-service-service.yaml
