apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.10.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: bbc-service
  name: bbc-service
spec:
  ports:
  - name: "10005"
    port: 10005
    targetPort: 10005
  selector:
    io.kompose.service: bbc-service
status:
  loadBalancer: {}
