apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.10.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: compute-service
  name: compute-service
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: compute-service
status:
  loadBalancer: {}
