apiVersion: v1
kind: Service
metadata:
  labels:
    app: compute-service
  name: compute-service
spec:
  ports:
  - name: "8080"
    port: 8080
  selector:
    app: compute-service
  

