apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-gateway
  name: redis-gateway
spec:
  ports:
  - name: "10006"
    port: 10006
    targetPort: 8080
  selector:
    app: redis-gateway
