apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.10.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: twitter-service
  name: twitter-service
spec:
  ports:
  - name: "10000"
    port: 10000
    targetPort: 10000
  selector:
    io.kompose.service: twitter-service
status:
  loadBalancer: {}
