apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-service
  name: web-service
spec:
  ports:
   - name: "8080"
     port: 8080
  selector:
    app: web-service    
  type: LoadBalancer

