apiVersion: v1
kind: Pod
metadata:
  name: bbc
spec:
  containers:
  - name: bbc
    image: index.docker.io/mattshallow/micro:bbc-v1
    imagePullPolicy: Always
    ports:
    - containerPort: 10005
  imagePullSecrets:
    - name: myregistrykey
  