apiVersion: v1
kind: Pod
metadata:
  name: twitter
spec:
  containers:
  - name: twitter
    image: index.docker.io/mattshallow/micro:twitter-v1
    imagePullPolicy: Always
    ports:
    - containerPort: 10000
  imagePullSecrets:
    - name: myregistrykey
  